[package]
name = "os_in_rust"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = { version = "0.9" }
spin = "0.9.8"
volatile = "0.2.6"
